$schemaver: 2.1
repo_url: https://github.com/byu-oit/awslogin
software:
  - aliases:
    assignment_group: gro:AD-Global Education Initiative
    ddd:
      business_domain:
      context_map_url:
      ubiquitous_language_url:
    developed_by_byu: true
    links:
      swagger_urls:
      system_documentation_url: https://github.com/byu-oit/awslogin
    maintained_by:
      - dsw88
      - pauldeden
    microservice: false
    name: awslogin
    notes:
    short_description: Script for CLI access to AWS via ADFS
    stages:
      development:
        aws_account:
        hosting_location: Other
        relationships:
          depends_on:
            db_read_only:
            db_read_write:
            software:
          reverse_proxy:
          runs_on:
            blade_server:
            rack_server:
            server_cluster:
            virtual_server:
          supports:
            service:
            software:
        urls:
          physical_url:
          product_page:
          virtual_url:
    technologies_used:
      - Python
      - AWS CodeBuild
      - Handel-Codepipeline
      - AWS CodePipeline
      - HTML
    type: command-line app
    data_sensitivity: confidential
    standard_change_template:
